[package]
name = "rust-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
web-sys = { version = "0.3", features = ["HtmlInputElement"] } # CHANGED: hinzuf√ºgen

serde = { version = "1", features = ["derive"] }
serde_json = "1"
gloo-net = "0.6.0"
wasm-bindgen-futures = "0.4"

